# Kairos node configuration
# Edit this file, then re-run deploy.sh

#VPS Configuration
# Connect to a VPS backbone? (yes/no)
VPS_ENABLED=no

# Only read if VPS_ENABLED=yes
VPS_HOST=""
VPS_PORT=""
VPS_NETWORK_NAME=""
#optional passphrase
VPS_PASSPHRASE=""

#Server only settings for install_server.sh
SERVER_LISTEN_IP=""
SERVER_LISTEN_PORT=""


#RNode Configuration 
# Connect an RNode (LoRa radio)? (yes/no)
RNODE_ENABLED=no

# Only read if RNODE_ENABLED=yes
# Find your port with: ls /dev/ttyUSB* /dev/ttyACM*
RNODE_PORT=""

# Defaults below are standard US 915MHz settings, change according to your location
RNODE_FREQUENCY=
RNODE_BANDWIDTH=
RNODE_TXPOWER=
RNODE_SPREADINGFACTOR=
RNODE_CODINGRATE=

#Optional, only radios with the same network name/passphrase will exchange traffic (IFAC)
RNODE_NETWORK_NAME=""
RNODE_PASSPHRASE=""

#Values allowed: full, boundary, gateway, access_point
RNODE_MODE=""
